#ifndef _XTIMER_CONFIG_H
#define _XTIMER_CONFIG_H

#include "xparameters.h"

#define XSLEEPTIMER_IS_TTCPS
#define XSLEEPTIMER_DEVICEID XPAR_PS7_TTC_0_DEVICE_ID
#define XTICKTIMER_IS_SCUTIMER
#define XTICKTIMER_DEVICEID XPAR_PS7_SCUTIMER_0_DEVICE_ID

#endif /* XTIMER_CONFIG_H */
